services:
  forge:
    image: chirvo/services/forge:latest
    container_name: forge
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /tmp/output/forge:/app/outputs
      - /mnt/fatboys/chirvo/sd/models:/app/models
      - /mnt/fatboys/chirvo/sd/embeddings:/app/embeddings
      - /mnt/fatboys/chirvo/sd/extensions/sd-webui-controlnet/models:/app/extensions/sd-webui-controlnet/models
    ports:
      - "7860:7860"
    shm_size: 2g
  a1111:
    image: chirvo/services/a1111:latest
    container_name: a1111
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /tmp/output/a1111:/app/outputs
      - /mnt/fatboys/chirvo/sd/models:/app/models
      - /mnt/fatboys/chirvo/sd/embeddings:/app/embeddings
      - /mnt/fatboys/chirvo/sd/extensions/sd-webui-controlnet/models:/app/extensions/sd-webui-controlnet/models
    ports:
      - "7860:7860"
    shm_size: 2g

  comfyui:
    image: chirvo/services/comfyui:latest
    container_name: comfyui
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboys/chirvo/sd/models/Stable-diffusion:/app/models/checkpoints
      - /mnt/fatboys/chirvo/sd/models/VAE:/app/models/vae
      - /mnt/fatboys/chirvo/sd/models/VAE-approx:/app/models/vae_approx
      - /mnt/fatboys/chirvo/sd/models/Lora:/app/models/loras
      - /mnt/fatboys/chirvo/sd/embeddings:/app/models/embeddings
      - /tmp/output/comfyui:/app/output
    ports:
      - "8188:8188"
    shm_size: 2g

  ollama:
    # image: ollama/ollama:rocm
    image: chirvo/services/ollama:latest
    container_name: ollama
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboys/chirvo/ollama:/root/.ollama
    ports:
      - "11434:11434"
    shm_size: 2g

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ./volumes/qdrant_storage:/qdrant/storage
    shm_size: 2g
      
  postgres:
    image: postgres:17-alpine
    # restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pgsqlUsr
      - POSTGRES_PASSWORD=pgsqlPwd
      - POSTGRES_DB=ragtool
    volumes:
      - ./volumes/postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    shm_size: 2g

  tika:
    image: apache/tika:latest
    container_name: tika
    # restart: unless-stopped
    ports:
      - 9998:9998
    shm_size: 2g

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    # restart: unless-stopped
    volumes:
      - ./volumes/open-webui:/app/backend/data
    depends_on:
      - ollama
      - tika
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    shm_size: 2g

  # https://containrrr.dev/watchtower/
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
