services:
  comfyui:
    image: chirvo/services/comfyui:latest
    container_name: comfyui
    restart: unless-stopped
    group_add:
      - video
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/kfd:/dev/kfd"
    volumes:
      - /mnt/fatboys/chirvo/volumes/comfyui/input:/app/input
      - /mnt/fatboys/chirvo/volumes/comfyui/user:/app/user
      - /mnt/fatboys/chirvo/volumes/comfyui/models:/app/models
      - /mnt/fatboys/chirvo/volumes/comfyui/custom_nodes:/app/custom_nodes
      - /tmp/comfyui/output:/app/model/output
      - /tmp/comfyui/temp:/app/temp
    ports:
      - "8188:8188"
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    shm_size: 8g
