services:
  forge:
    image: chirvo/forge:latest
    container_name: forge
    # restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /tmp/output/forge:/app/outputs
      - /mnt/mirror/chirvo/sd/models:/app/models
      - /mnt/mirror/chirvo/sd/embeddings:/app/embeddings
    ports:
      - "7860:7860"
    shm_size: 8g
