services:
  kokoro-tts:
    image: chirvo/services/kokoro-tts-api:latest
    container_name: kokoro-tts
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app:/app/models
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
      - MIOPEN_LOG_LEVEL=3
    devices:
      - /dev/dri
      - /dev/kfd
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
    shm_size: 512m
    networks:
      - open-webui_network
