services:
  kokoro-tts:
    image: chirvo/services/kokoro-tts-fastapi:latest
    container_name: kokoro-tts
    restart: unless-stopped
    environment:
      - MIOPEN_LOG_LEVEL=3
    devices:
      - /dev/dri
      - /dev/kfd
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ports:
      - "8880:8880"
    ipc: host
    shm_size: 512m
