services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - ../../volumes/open-webui:/app/backend/data
    depends_on:
      - ollama
      - valkey
      - tika
      - kokoro-tts
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
      - ENABLE_WEBSOCKET_SUPPORT="true"
      - WEBSOCKET_MANAGER="redis"
      - WEBSOCKET_REDIS_URL="redis://valkey:6379/1"
    shm_size: 512m
