name: kokoro-fastapi
services:
  kokoro-tts-api:
    image: chirvo/services/kokoro-tts-api
    container_name: kokoro-tts-api
    ports:
      - "8880:8880"
    # volumes:
      # - ../volumes/kokoro-tts/voices:/app/api/src/voices  # Mount voices for persistence
    environment:
      - PYTHONPATH=/app:/app/models
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
      # This suppresses excessive warning logs. Probably not a good idea to suppress, but no other solution found
      # (see https://github.com/ROCm/MIOpen/issues/2981)
      - MIOPEN_LOG_LEVEL=3
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
    ipc: host
