services:
  ollama:
    image: chirvo/services/ollama:latest
    container_name: ollama
    restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboys/chirvo/ollama:/root/.ollama
    ports:
      - "11434:11434"
    shm_size: 2g

  tika:
    image: apache/tika:latest-full
    container_name: tika
    restart: unless-stopped
    ports:
      - 9998:9998
    shm_size: 2g

  # FIXME: Not working.
  redis:
    image: valkey/valkey:8.0.1-alpine
    container_name: redis
    volumes:
      - ../volumes/open-webui_redis:/data
    command: "valkey-server --save 30 1"
    healthcheck:
      test: "[ $$(valkey-cli ping) = 'PONG' ]"
      start_period: 5s
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    shm_size: 2g
        
  openedai-speech:
    image: chirvo/services/openedai-speech:latest
    container_name: openedai-speech
    ports:
      - "8000:8000"
    volumes:
      - ../openedai-speech/voices:/app/voices
      - ../openedai-speech/config:/app/config
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    group_add:
      - video
      - audio
    ipc: host
    shm_size: 2g
    environment:
      - USE_ROCM=1
      # - TTS_HOME=voices
      - HF_HOME=voices
      # - PRELOAD_MODEL=xtts
      - PRELOAD_MODEL=xtts_v2.0.2
      # - EXTRA_ARGS=--log-level DEBUG --unload-timer 300

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - ../volumes/open-webui:/app/backend/data
    depends_on:
      - ollama
      # - redis
      - tika
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
      - ENABLE_WEBSOCKET_SUPPORT="true"
      - WEBSOCKET_MANAGER="redis"
      - WEBSOCKET_REDIS_URL="redis://redis:6379/1"
    extra_hosts:
      - host.docker.internal:host-gateway
    shm_size: 2g

