services:
  ollama:
    image: chirvo/services/ollama:latest
    container_name: ollama
    restart: unless-stopped
    group_add:
      - video
    devices:
      - /dev/dri
      - /dev/kfd
    security_opt:
      - seccomp=unconfined
    volumes:
      - /mnt/fatboys/chirvo/ollama:/root/.ollama
    ports:
      - "11434:11434"
    shm_size: 2g

  tika:
    image: apache/tika:latest-full
    container_name: tika
    restart: unless-stopped
    ports:
      - 9998:9998
    shm_size: 2g

  # FIXME: Not working.
  redis:
    image: valkey/valkey:latest
    container_name: redis
    volumes:
      - ../volumes/redis:/data
    command: "valkey-server --save 30 1"
    healthcheck:
      test: "[ $$(valkey-cli ping) = 'PONG' ]"
      start_period: 5s
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    shm_size: 2g
        
  kokoro-tts:
    image: chirvo/services/kokoro:latest
    container_name: kokoro
    restart: unless-stopped
    group_add:
      - video
    devices:
      - /dev/dri
      - /dev/kfd
    security_opt:
      - seccomp=unconfined
    ports:
      - 8880:8880
    shm_size: 2g

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - ../volumes/open-webui:/app/backend/data
    depends_on:
      - ollama
      - tika
      - kokoro-tts
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
      - ENABLE_WEBSOCKET_SUPPORT="true"
      - WEBSOCKET_MANAGER="redis"
      - WEBSOCKET_REDIS_URL="redis://redis:6379/1"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    shm_size: 2g

