services:
  ollama:
    image: chirvo/services/ollama:latest
    container_name: ollama
    restart: unless-stopped
    group_add:
      - video
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/kfd:/dev/kfd'
    volumes:
      - /mnt/fatboys/chirvo/ollama:/root/.ollama
    ports:
      - "11434:11434"
    shm_size: 2g

  tika:
    image: apache/tika:latest-full
    container_name: tika
    restart: unless-stopped
    ports:
      - 9998:9998
    shm_size: 2g

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - ../volumes/open-webui:/app/backend/data
    depends_on:
      - ollama
      - tika
    ports:
      - 8080:8080
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - host.docker.internal:host-gateway
    shm_size: 2g

